### ISSUE TITLE
获取Discord凭证失败

### ISSUE THREAD

**Issue by inory121** [HCLonely/auto-task#2]
- [x] 我已经将脚本更新到了[最新版](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.user.js) | I have updated this script to the [latest version](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.user.js).
- [x] 我尝试过使用[兼容版](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.compatibility.user.js)但没有解决 | I have updated this script to the [compatible version](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.compatibility.user.js) but not solved.
- [x] 我已经查看了[常见问题解决办法](https://auto-task-doc.js.org/FAQ/)但没有解决 | I have seen [FAQ](https://auto-task-doc.js.org/en/FAQ/) but not solved.
- [x] 我已经查看了[用前必读](https://auto-task-doc.js.org/guide/#用前必读)但没有解决 | I have seen [READ ME FIRST](https://auto-task-doc.js.org/en/guide/#read-me-first) but not solved.
- [x] 我已经查看了[issues](https://github.com/HCLonely/auto-task-v4/issues)但没有解决 | I have seen [issues](https://github.com/HCLonely/auto-task-v4/issues) but not solved.

**关于哪一个网站，最好提供具体网址（必需）**[支持的网站](https://auto-task-doc.js.org/guide/#支持的网站)

https://discord.com/

**使用的浏览器和脚本管理器**

Chrome
Tampermonkey

**错误信息或截图(重要)**

![image](https://user-images.githubusercontent.com/35392664/150276803-3cd3044e-52ee-4e73-a18c-7b26d1a369b6.png)
![image](https://user-images.githubusercontent.com/35392664/150276844-fe9aa1cf-1b7f-42fd-9881-8569bd1388d3.png)
![image](https://user-images.githubusercontent.com/35392664/150276895-499617a8-5c00-4ebb-9fc4-9f93112d1dfa.png)

**Comment by HCLonely** [comment]
已修复，V4版本不需要辅助脚本
