### ISSUE TITLE
大佬求教，报错 Steam 初始化失败（600）

### ISSUE THREAD

**Issue by ArsenicX** [HCLonely/auto-task#24]
### 提交BUG前请先阅读以下内容

- [X] 我已经将脚本更新到了[最新版](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.user.js) | I have updated this script to the [latest version](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.user.js).
- [X] 我尝试过使用[兼容版](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.compatibility.user.js)但没有解决 | I have updated this script to the [compatible version](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.compatibility.user.js) but not solved.
- [X] 我已经查看了[常见问题解决办法](https://auto-task-doc.js.org/FAQ/)但没有解决 | I have seen [FAQ](https://auto-task-doc.js.org/en/FAQ/) but not solved.
- [X] 我已经查看了[用前必读](https://auto-task-doc.js.org/guide/#用前必读)但没有解决 | I have seen [READ ME FIRST](https://auto-task-doc.js.org/en/guide/#read-me-first) but not solved.
- [X] 我已经查看了[issues](https://github.com/HCLonely/auto-task-v4/issues)但没有解决 | I have seen [issues](https://github.com/HCLonely/auto-task-v4/issues) but not solved.

### 问题描述

使用了最新版本脚本，但是还是提示这个错误。尝试打开steam商店首页和社区首页去刷新配置也还是报错：
> 正在获取Steam用户社区链接...Success:Load(600)
Steam 初始化失败！

### 关于哪一个网站

https://gleam.io/GyFX8/scream-or-die-steam-key

### 浏览器版本

```json
Chrome Version 126.0.6478.61 (Official Build) (x86_64)
```

### 脚本管理器版本

TamperMonkey 5.2.0

### 脚本版本

正式版&兼容版 4.4.4

### 错误信息

```shell
控制台没有报错信息，相关的只有这几条：

Auto-Task[Load]: 脚本开始加载
VM1646:9 injected: [TimerHook] UI component 'legacyUi' loaded.
userscript.html?name=Maximize-Video.user.js&id=26aa4ffb-3cae-49c0-9bfa-6a10f5d2fc45:66 [2024-06-24 23:40:32][Maximize Video] > Ready
userscript.html?name=auto-task-v4.compatibility.user.js&id=8a09ae9f-2889-4b61-b30b-471585029c49:167 

点击【做任务】之后，就提示steam初始化失败。但是控制台还是没有新的输出
```

### 执行日志

```auto
正在获取Steam用户社区链接...Success:Load(600)
Steam 初始化失败！
```

### 附加截图

<img width="1611" alt="image" src="https://github.com/HCLonely/auto-task-v4/assets/40692855/1938d40a-fd55-4265-a1e9-5b2bb201892b">

**Comment by HCLonely** [comment]
已知BUG，下版本修复
可以先回退到[4.4.1](https://github.com/HCLonely/auto-task-v4/releases/tag/v4.4.1)版本

**Comment by RomantikSigara** [comment]
4.4.14也是出现这个

**Comment by ArsenicX** [comment]
@HCLonely 大佬，我也是这样，昨天的新版本提示

脚本版本：4.5.0
脚本地址：https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.user.js
Chrome版本：Version 130.0.6723.119 (Official Build) (arm64)
任务地址：https://givee.club/zh/event/881

错误提示：
正在获取Steam用户社区链接...重试
正在获取Steam用户社区链接...Error:重定向
（此时会自动打开个人资料页面，但是重新做任务还是弹出同样的提示，然后又一次打开个人资料页面）

错误截图：
<img width="816" alt="SCR-20241116-mbig" src="https://github.com/user-attachments/assets/4982096b-433a-48c0-8b74-ffa8647e2230">

尝试解决：
重新安装脚本、彻底退出steam社区和商店、关闭去广告拓展，都没用
但是使用[ 4.4.1版本 ](https://politepol.com/fd/ANQJ0FQgeqCI.xml)就可以



> 4.4.14也是出现这个
