### ISSUE TITLE
[BUG] 脚本报错: Gleam.verifyTask

### ISSUE THREAD

**Issue by Mishasama** [HCLonely/auto-task#29]
### 提交BUG前请先阅读以下内容

- [X] 我已经将脚本更新到了[最新版](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.user.js) | I have updated this script to the [latest version](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.user.js).
- [X] 我尝试过使用[兼容版](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.compatibility.user.js)但没有解决 | I have updated this script to the [compatible version](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.compatibility.user.js) but not solved.
- [X] 我已经查看了[常见问题解决办法](https://auto-task-doc.js.org/FAQ/)但没有解决 | I have seen [FAQ](https://auto-task-doc.js.org/en/FAQ/) but not solved.
- [X] 我已经查看了[用前必读](https://auto-task-doc.js.org/guide/#用前必读)但没有解决 | I have seen [READ ME FIRST](https://auto-task-doc.js.org/en/guide/#read-me-first) but not solved.
- [X] 我已经查看了[issues](https://github.com/HCLonely/auto-task-v4/issues)但没有解决 | I have seen [issues](https://github.com/HCLonely/auto-task-v4/issues) but not solved.

### 关于哪一个网站

https://gleam.io/e3J9F/free-x2000-sunland-town-steam-keys

### 浏览器版本

```json
{
    "browser": "Chrome",
    "browserZH": "Chrome",
    "browserVersion": "128.0.0.0",
    "os": "Windows",
    "osVersion": "10.0",
    "device": "PC",
    "engine": "WebKit"
}
```

### 脚本管理器版本

Tampermonkey 5.2.3

### 脚本版本

4.4.9

### 错误信息

```shell
TypeError: Cannot set properties of undefined (setting 'value')
    at Gleam.verifyTask (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=auto-task-v4.user.js&id=d220f7ad-6943-4a09-a1dc-e209435fb1ff:9539:25)
```

### 执行日志

```auto
正在初始化...Success
正在获取并处理任务信息...Success
正在获取Gleam任务链接...Success
正在获取Gleam任务链接...Success
正在做Gleam任务...Success
正在做Gleam任务...Success
所有任务已完成！
正在验证任务...
```

**Comment by HCLonely** [comment]
已修复

**Comment by Mishasama** [comment]
我也不知道这是咋回事，反正你说修了那就行，我相信你。<s>（毕竟我也不知道要怎么去测试）</s>
