### ISSUE TITLE
Twitter 出错 + Discord 无限弹出问题复活

### ISSUE THREAD

**Issue by Mishasama** [HCLonely/auto-task#30]
### 提交BUG前请先阅读以下内容

- [X] 我已经将脚本更新到了[最新版](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.user.js) | I have updated this script to the [latest version](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.user.js).
- [X] 我尝试过使用[兼容版](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.compatibility.user.js)但没有解决 | I have updated this script to the [compatible version](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.compatibility.user.js) but not solved.
- [X] 我已经查看了[常见问题解决办法](https://auto-task-doc.js.org/FAQ/)但没有解决 | I have seen [FAQ](https://auto-task-doc.js.org/en/FAQ/) but not solved.
- [X] 我已经查看了[用前必读](https://auto-task-doc.js.org/guide/#用前必读)但没有解决 | I have seen [READ ME FIRST](https://auto-task-doc.js.org/en/guide/#read-me-first) but not solved.
- [X] 我已经查看了[issues](https://github.com/HCLonely/auto-task-v4/issues)但没有解决 | I have seen [issues](https://github.com/HCLonely/auto-task-v4/issues) but not solved.

### 问题描述

你的代码是不是回滚了？
Twitter 和 Discord 的老问题又回来了。

### 关于哪一个网站

https://gleam.io/EyHVw/new-suicide-guy-vr-steam-giveaway

### 浏览器版本

```json
Google Chrome	128.0.6613.138
```

### 脚本管理器版本

5.2.3

### 脚本版本

4.4.12

### 错误信息

```shell
userscript.html?name=auto-task-v4.user.js&id=d220f7ad-6943-4a09-a1dc-e209435fb1ff:136 Auto-Task[Load]: 脚本开始加载
16:40:27.475 userscript.html?name=auto-task-v4.user.js&id=d220f7ad-6943-4a09-a1dc-e209435fb1ff:10824 Auto-Task[Load]: 脚本加载完成
```

### 执行日志

```auto
正在初始化...Success
正在获取并处理任务信息...Success
正在验证Twitter凭证...Error:(403)
正在获取Steam用户社区链接...Success
正在更新Twitter凭证...Success
正在验证Twitter凭证...Error:(403)
Twitter 初始化失败！
SteamCommunity 初始化成功！
```

### 附加截图

![image](https://github.com/user-attachments/assets/49b8774b-0d37-4421-b7da-51456e1e90d6)

**Comment by HCLonely** [comment]
经测试未出现上述问题

**Comment by Mishasama** [comment]
又是chrome专属的谜之profile bug吗？那我先关了吧，找到原因再开。
