### ISSUE TITLE
无法完成【更新Steam社区凭证】动作

### ISSUE THREAD

**Issue by Mishasama** [HCLonely/auto-task#34]
### 提交BUG前请先阅读以下内容

- [X] 我已经将脚本更新到了[最新版](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.user.js) | I have updated this script to the [latest version](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.user.js).
- [X] 我尝试过使用[兼容版](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.compatibility.user.js)但没有解决 | I have updated this script to the [compatible version](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.compatibility.user.js) but not solved.
- [X] 我已经查看了[常见问题解决办法](https://auto-task-doc.js.org/FAQ/)但没有解决 | I have seen [FAQ](https://auto-task-doc.js.org/en/FAQ/) but not solved.
- [X] 我已经查看了[用前必读](https://auto-task-doc.js.org/guide/#用前必读)但没有解决 | I have seen [READ ME FIRST](https://auto-task-doc.js.org/en/guide/#read-me-first) but not solved.
- [X] 我已经查看了[issues](https://github.com/HCLonely/auto-task-v4/issues)但没有解决 | I have seen [issues](https://github.com/HCLonely/auto-task-v4/issues) but not solved.

### 问题描述

现在浏览器默认政策严格屏蔽弹窗，且几乎没有任何交互提示，除非专业用户特意去修改设置。
脚本应考虑使用弹窗以外的功能来完成任务。

### 关于哪一个网站

https://gleam.io/

### 浏览器版本

```json
Google Chrome	130.0.6723.117
```

### 脚本管理器版本

TM 5.3.2

### 脚本版本

4.4.18

### 错误信息

```shell
03:31:09.605 userscript.html?name=auto-task-v4.user.js&id=d220f7ad-6943-4a09-a1dc-e209435fb1ff:137 Auto-Task[Load]: 脚本开始加载
03:31:10.466 userscript.html?name=auto-task-v4.user.js&id=d220f7ad-6943-4a09-a1dc-e209435fb1ff:10857 Auto-Task[Load]: 脚本加载完成
```

### 执行日志

```auto
正在初始化...Success
正在获取并处理任务信息...Success
正在获取Steam用户社区链接...重试
正在获取Steam用户社区链接...Error:重定向
正在更新Steam社区凭证...
```

### 附加截图

![image](https://github.com/user-attachments/assets/7b6ce127-f9d4-4910-9646-0a3550a1f787)
![image](https://github.com/user-attachments/assets/e105f299-4ffc-4615-95a7-1ded674eedb9)

**Comment by Mishasama** [comment]
![image](https://github.com/user-attachments/assets/bc29b605-ab5e-497e-8a8b-5965b93bb79e)
最新版本打开 https://steamcommunity.com/my 后就没有下文了，也不会自动关闭。手动返回任务页面显示如上。

**Comment by HCLonely** [comment]
截一下弹出的窗口

**Comment by Mishasama** [comment]
> 截一下弹出的窗口

只是一个已经登入了的自己的社区profile页面而已，没有任何看起来像是脚本添加上去的元素。（比如右下角日志）

**Comment by HCLonely** [comment]
最终网址是什么？
在弹出的页面打开控制台，输入`window.name`

**Comment by Mishasama** [comment]
![image](https://github.com/user-attachments/assets/4de5ac24-a967-4ddd-831f-77508f28d40b)
https://steamcommunity.com/id/ylenoLCH/

以前只是部分功能失效，现在是完全报废了。

**Comment by ztw321** [comment]
![1](https://github.com/user-attachments/assets/d4276f82-772f-4569-96e0-1924820d74dd)
脚本打开https://steamcommunity.com/my/ 后跳转到我的steam主页后输入window.name显示 `ATv4_updateCommunityAuth`

**Comment by HCLonely** [comment]
已修复，再试试

**Comment by Mishasama** [comment]
用是能用了，但经常需要做一次后刷新页面再做一次，不然有部分弹窗倒计时啥的在验证阶段完成不了。
现在脚本会打开一个无效的分页来模拟观看任务，但似乎兼容性不是很好，容易卡流程（比如时间到了之后关闭分页返回的不是任务页面），也吃系统资源。能不能利用脚本来模拟任务页面处于后台的状态呢？

**Comment by HCLonely** [comment]
暂时无法实现，弹出新窗口就是为了走倒计时

**Comment by Mishasama** [comment]
暂时没发现有其它相关问题了
