### ISSUE TITLE
Gleam 无法完成等待观看任务

### ISSUE THREAD

**Issue by Mishasama** [HCLonely/auto-task#39]
### 提交BUG前请先阅读以下内容

- [X] 我已经将脚本更新到了[最新版](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.user.js) | I have updated this script to the [latest version](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.user.js).
- [X] 我尝试过使用[兼容版](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.compatibility.user.js)但没有解决 | I have updated this script to the [compatible version](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.compatibility.user.js) but not solved.
- [X] 我已经查看了[常见问题解决办法](https://auto-task-doc.js.org/FAQ/)但没有解决 | I have seen [FAQ](https://auto-task-doc.js.org/en/FAQ/) but not solved.
- [X] 我已经查看了[用前必读](https://auto-task-doc.js.org/guide/#用前必读)但没有解决 | I have seen [READ ME FIRST](https://auto-task-doc.js.org/en/guide/#read-me-first) but not solved.
- [X] 我已经查看了[issues](https://github.com/HCLonely/auto-task-v4/issues)但没有解决 | I have seen [issues](https://github.com/HCLonely/auto-task-v4/issues) but not solved.

### 问题描述

也就点击展开任务，然后等5秒再点击继续而已。

### 关于哪一个网站

https://gleam.io/V3Yij/free-x2500-triple-otakus-puzzle

### 浏览器版本

```json
Google Chrome	131.0.6778.109
```

### 脚本管理器版本

TM 5.3.3

### 脚本版本

4.5.5

### 错误信息

```shell
userscript.html?name=auto-task-v4.user.js&id=d220f7ad-6943-4a09-a1dc-e209435fb1ff:145 Auto-Task[Load]: 脚本开始加载
02:19:28.055 userscript.html?name=auto-task-v4.user.js&id=d220f7ad-6943-4a09-a1dc-e209435fb1ff:10875 Auto-Task[Load]: 脚本加载完成
02:19:28.055 userscript.html?name=auto-task-v4.user.js&id=d220f7ad-6943-4a09-a1dc-e209435fb1ff:611 Auto-Task[Debug]:
httpRequest @ userscript.html?name=auto-task-v4.user.js&id=d220f7ad-6943-4a09-a1dc-e209435fb1ff:611
checkUpdate @ userscript.html?name=auto-task-v4.user.js&id=d220f7ad-6943-4a09-a1dc-e209435fb1ff:10643
updateChecker @ userscript.html?name=auto-task-v4.user.js&id=d220f7ad-6943-4a09-a1dc-e209435fb1ff:10714
loadScript @ userscript.html?name=auto-task-v4.user.js&id=d220f7ad-6943-4a09-a1dc-e209435fb1ff:10896
```

### 执行日志

```auto
正在验证任务...
已尝试验证所有任务，验证失败的任务请尝试手动验证或完成！
```

### 附加截图

![image](https://github.com/user-attachments/assets/920122f4-3a2e-463c-91cf-bfd6470268b7)

**Comment by HCLonely** [comment]
这个网站关于计时的任务实现起来有很多问题，暂无适配计划
