### ISSUE TITLE
获取Discord凭证失败

### ISSUE THREAD

**Issue by Gnoriz-Tea** [HCLonely/auto-task#6]
### 提交BUG前请先阅读以下内容

- [X] 我已经将脚本更新到了[最新版](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.user.js) | I have updated this script to the [latest version](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.user.js).
- [X] 我尝试过使用[兼容版](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.compatibility.user.js)但没有解决 | I have updated this script to the [compatible version](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.compatibility.user.js) but not solved.
- [X] 我已经查看了[常见问题解决办法](https://auto-task-doc.js.org/FAQ/)但没有解决 | I have seen [FAQ](https://auto-task-doc.js.org/en/FAQ/) but not solved.
- [X] 我已经查看了[用前必读](https://auto-task-doc.js.org/guide/#用前必读)但没有解决 | I have seen [READ ME FIRST](https://auto-task-doc.js.org/en/guide/#read-me-first) but not solved.
- [X] 我已经查看了[issues](https://github.com/HCLonely/auto-task-v4/issues)但没有解决 | I have seen [issues](https://github.com/HCLonely/auto-task-v4/issues) but not solved.

### 关于哪一个网站

https://discord.com/

### 浏览器版本

```json
Chrome
```

### 脚本管理器版本

Tampermonkey

### 脚本版本

v4.1.21-beta

### 错误信息

```shell
DevTools 无法加载来源映射：无法加载 chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/sm/dad6bd9f16f12d9db4b0e4eaae5c5f614cb87edf6808e087afac03051831773b.map 的内容：HTTP 错误：状态代码 404，net::ERR_UNKNOWN_URL_SCHEME
```

### 附加截图

![屏幕截图 2022-01-29 154738](https://user-images.githubusercontent.com/66054917/151652860-cb2fa77f-db28-4e43-a80e-af4c6061b9b9.png)
![屏幕截图 2022-01-29 154756](https://user-images.githubusercontent.com/66054917/151652864-42c839d4-acdc-4ef5-8da5-f2d72f571621.png)
![屏幕截图 2022-01-29 155001](https://user-images.githubusercontent.com/66054917/151652865-e6647c93-97d0-46b2-8bc4-35394122a36c.png)
[](url
[Discord.txt](https://github.com/HCLonely/auto-task-v4/files/7963237/Discord.txt)
)

**Comment by HCLonely** [comment]
请查看Discord是否已登录以及这个网页能不能正常打开https://discord.com/channels/@me

**Comment by Gnoriz-Tea** [comment]
> 请查看Discord是否已登录以及这个网页能不能正常打开https://discord.com/channels/@me

可以
![屏幕截图 2022-01-29 160939](https://user-images.githubusercontent.com/66054917/151653284-f1117fe2-951f-40c7-a707-6d5cd053b815.png)

**Comment by HCLonely** [comment]
在获取一次Discord凭证试试

**Comment by Gnoriz-Tea** [comment]
还是不行
![屏幕截图 2022-01-29 161450](https://user-images.githubusercontent.com/66054917/151653435-bd194012-ab5c-4622-9692-26aa5301a80c.png)

**Comment by HCLonely** [comment]
安装这个再截一下控制台
https://github.com/HCLonely/auto-task-v4/raw/main/dist/auto-task-v4.debug.user.js

**Comment by Gnoriz-Tea** [comment]
[discord.txt](https://github.com/HCLonely/auto-task-v4/files/7963307/discord.txt)

**Comment by Gnoriz-Tea** [comment]
感谢！
