### ISSUE TITLE
正在获取Key...Error:(200)

### ISSUE THREAD

**Issue by stickerx** [HCLonely/auto-task#7]
### 提交BUG前请先阅读以下内容

- [X] 我已经将脚本更新到了[最新版](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.user.js) | I have updated this script to the [latest version](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.user.js).
- [X] 我尝试过使用[兼容版](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.compatibility.user.js)但没有解决 | I have updated this script to the [compatible version](https://github.com/HCLonely/auto-task-new/raw/main/dist/auto-task-v4.compatibility.user.js) but not solved.
- [ ] 我已经查看了[常见问题解决办法](https://auto-task-doc.js.org/FAQ/)但没有解决 | I have seen [FAQ](https://auto-task-doc.js.org/en/FAQ/) but not solved.
- [X] 我已经查看了[用前必读](https://auto-task-doc.js.org/guide/#用前必读)但没有解决 | I have seen [READ ME FIRST](https://auto-task-doc.js.org/en/guide/#read-me-first) but not solved.
- [X] 我已经查看了[issues](https://github.com/HCLonely/auto-task-v4/issues)但没有解决 | I have seen [issues](https://github.com/HCLonely/auto-task-v4/issues) but not solved.

### 问题描述

i have solve all quest
.Error:(200)

### 关于哪一个网站

freeanywhere*net

### 浏览器版本

```json
Google Chrome

Version 97.0.4692.99 (Official Build) (64-bit)
```

### 脚本管理器版本

Tampermonkey 4.13

### 脚本版本

 4.2.1

### 错误信息

```shell
正在获取Key...Error:(200)
```

### 执行日志

```auto
正在初始化...Success
正在获取并处理任务信息...Success
正在验证 Vk 凭证...Success
正在更新Steam商店凭证...Success
正在更新Steam社区凭证...Success
SteamStore 初始化成功！
SteamCommunity 初始化成功！
Vk 初始化成功！
正在获取Vk任务Id[goodhalavya]...Success
正在获取Steam组Id[gamesforfarm]...Success
正在退出Steam组[gamesforfarm]...Success
正在获取Vk任务Id[gamesforfarm]...Success
正在从Steam愿望单移除游戏[1810210✘⚙]...Success
正在获取Vk任务Id[steam_level_u]...Success
正在取关Steam鉴赏家[8166142]...Success
正在退出Vk社区[goodhalavya]...Success
正在退出Vk组[gamesforfarm]...Success
正在退出Vk社区[steam_level_u]...Success
所有任务已完成！
正在获取Key...Error:(200)
正在获取Key...Error:(200)
```

### 附加截图

![2022-02-05_151820](https://user-images.githubusercontent.com/41187653/152646036-3166a2b5-4803-4ade-a2d4-8cf640ae2cd0.jpg)

**Comment by HCLonely** [comment]
请尝试使用`验证任务`按钮

**Comment by HCLonely** [comment]
`验证任务`：验证所有任务且任务完成后自动获取Key
`获取Key`：尝试获取Key。如果你没有完成并验证所有任务，则会提示`Error:(200)`
